### ISSUE TITLE
CSS Bug with header bar

### ISSUE THREAD

**Issue by mariohuq** [jupyter/jupyter.github.io#402]
When I use link <https://jupyter.org/install#install-with-pip> I get this

![image](https://user-images.githubusercontent.com/15021607/111931660-66c2b380-8b07-11eb-8c6c-bb2fb1ca7062.png)

But I expect this:

![image](https://user-images.githubusercontent.com/15021607/111931698-8063fb00-8b07-11eb-913f-86d0a77215e6.png)

So, when I navigate to the named link, the navbar blocks the view.

**Comment by mariohuq** [comment]
I found a fix [there](https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/):

```css
html {
  scroll-padding-top: 70px; /* height of sticky header */
}
```
